import "./globals.css";
import { cn } from "@/lib/utils";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/themeProvider";
import { ModalProvider } from "@/components/providers/modalProvider";
import { SocketProvider } from "@/components/providers/socketProvider";
import { QueryProvider } from "@/components/providers/queryProvider";
import { Loader } from "@/components/Extra/loader";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Discord ",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#161616]")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            // disableTransitionOnChange
            storageKey="discord-theme"
          >
            <SocketProvider>
              <ModalProvider />
              <QueryProvider>
                <Loader />
                {children}
              </QueryProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default layout;
